#! /bin/sh

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd >/dev/null || sxhkd &

# eww close bar
# eww open bar
polybar bar &
polybar-ctl t

# set background
feh --bg-scale ~/.local/wallpapers/island_midnight.png --no-feh

killall "nm-applet"
nm-applet &

killall "lxsession"
lxsession &

killall "dunst"
dunst &
#idlehook &
killall "ibus-daemon"
ibus-daemon -drR

# see picom config for more details
killall "picom"
picom --experimental-backends -b

# show the tray options
killall "udiskie"
udiskie --tray &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 3
bspc config border_normal_color "#c2cae2"
bspc config active_border_color "#92bbed"
bspc config focused_border_color "#92bbed"
bspc config window_gap 5
bspc config left_padding 10
bspc config right_padding 10

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme alternate

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize-corner

bspc rule -a discord desktop='^5'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
