# entry point
@default_files = ('main.tex');

# pdf settings
$dvi_mode = 0;
$postscript_mode = 0;

$pdf_previewer = 'start zathura';

# compile settings
$out_dir = './build';
$aux_dir = './build';

# shell escape is for minted package
$pdflatex = "pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1 -shell-escape"
