#! /usr/bin/env bash

startorstop() {
	if systemctl status "$1" | grep -q "inactive"; then
		if sudo systemctl enable --now "$1"; then
			echo "Restarting $1 service"
		else
			echo "Cannot restart $1 service"
		fi
	else
		sudo systemctl stop mongodb
		if sudo systemctl disable mongodb; then
			echo "Stopping $1 service"
		else
			echo "Cannot stop $1 service"
		fi
	fi
}

case "$1" in
mongo | mongodb)
	startorstop mongodb
	;;
maria | mariadb)
	startorstop maria
	;;
post | postgres | postgresql | postgresqldb)
	startorstop postgresql
	;;
redis)
	startorstop redis
	;;
*)
	echo "I don't know what to do?"
	exit 1
	;;
esac
