#! /usr/bin/env bash

case "$1" in
i | integrated)
	sudo sed -i '/mode/c\  "mode": "Integrated",' /etc/supergfxd.conf
	;;
h | hybrid)
	sudo sed -i '/mode/c\  "mode": "Hybrid",' /etc/supergfxd.conf
	;;
c | compute)
	sudo sed -i '/mode/c\  "mode": "Compute",' /etc/supergfxd.conf
	;;
d | dedicated)
	sudo sed -i '/mode/c\  "mode": "Dedicated",' /etc/supergfxd.conf
	;;
*)
	echo "What are you trying to do? Use i for integratd, h for hybrid, c for compute and d for dedicated" >&2
	exit 1
	;;
esac
