#! /usr/bin/env fish

set subreddits archlinux unixporn unix linux piracy privacy programmerhumor ChineseLanguage classicalchinese Cantonese linguisticshumor languagelearningjerk learnthai Minecraft StardewValley askreddit Hermitcraft AnimalCrossing RimWorld ThirdLifeSMP engrish keming

set domain "localhost:9090"
# printf will print an extra + at the end
set multireddit $(printf "%s+" $subreddits | string sub -e -1)

# output the final url
echo "http://$domain/r/$multireddit"
