#! /usr/bin/env bash
#
# ask neovim to open itself at the project directory
# instead of the current directory

if [[ -n "$1" ]]; then
	if [[ -d "$1" ]]; then
		cd "$1" && nvim .
	else
		nvim "$1"
	fi
else
	nvim
fi
