#! /usr/bin/bash

{ nvidia-smi && prime-run "$@"; } || exec "$@"

# path="$HOME/.local/scripts/prime-or-not-status"
# if (( is_prime )); then
#   printf "it is started with nvidia gpu\nArgs: %s" "$*" > "$path"
# else
#   printf "it is started with integrated gpu\nArgs: %s" "$*" > "$path"
# fi
