#! /usr/bin/env fish

set project_dir "$HOME/Documents/sources"

# the first line is the root, so we remove it
set chosen $(find $project_dir -maxdepth 1 -type d -printf "%P\n" | tail +2 | rofi -p "Project" -dmenu)

# if there is nothing, stop the script
if test -n "$chosen"
  vscodium "$PROJECT_PATH/$chosen"
end

