#! /bin/bash

RECONNECT="Reconnect to Last Server"
DISCONNECT="Disconnect"
REMEMBER="Remember Current Server"
RANDOM_INSTANCE="Random"
NO_KILL_SWITCH="Disable Kill Switch"

last_server="none"

unkill() {
	protonvpn-cli ks --off
}

ask() {
	# no active connection
	if protonvpn-cli s | grep -q "No"; then
		# do not show reconnect option if there is no such file
		if [ "$last_server" == "none" ]; then
			chosen=$(printf "%s\n%s" "$REMEMBER" "$RANDOM_INSTANCE" | rofi -dmenu -p "VPN")
		else
			chosen=$(
				printf "%s\n%s\n%s\n%s" "$RECONNECT" "$REMEMBER" "$RANDOM_INSTANCE" "$NO_KILL_SWITCH" | rofi -dmenu -p "VPN"
			)
		fi
	else
		chosen=$(printf "%s\n%s\n%s" "$DISCONNECT" "$REMEMBER" "$RANDOM_INSTANCE" | rofi -dmenu -p "VPN")
	fi
}

connect() {
	protonvpn-cli c -f
	status_text=$(protonvpn-cli s)
	echo "$status_text"
}

reconnect() {
	protonvpn-cli c "$last_server"
}

BASE_SAVE_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/rofi-proton-vpn"
BASE_SAVE_FILE="${BASE_SAVE_PATH}/last_server"

save() {
	server=$(protonvpn-cli s | grep "Server:" | awk -F: '{ print $2 }' | sed 's/^[ \t]*//')
	mkdir -p "$BASE_SAVE_PATH"
	echo "$server" >"$BASE_SAVE_FILE"
}

lastserver() {
	[ -f "$BASE_SAVE_FILE" ] && last_server=$(cat "$BASE_SAVE_FILE")
}

lastserver
ask

# see what has the user chosen
case "$chosen" in
"$RECONNECT")
	unkill
	reconnect
	;;
"$REMEMBER")
	save
	;;
"$DISCONNECT")
	protonvpn-cli d
	unkill
	;;
"$RANDOM_INSTANCE")
	unkill
	protonvpn-cli c -f
	save
	;;
"$NO_KILL_SWITCH")
	unkill
	;;
esac
