#! /usr/bin/env bash

options=("Lock 🔒" "Suspend 💤" "Shutdown 🔌" "Restart 💻" "Logout 🔑")

chosen=$(printf "%s\n" "${options[@]}" | rofi -p "Power" -dmenu)

ask_graphics() {
	mode=("No Change" "Integrated" "Hybrid" "Dedicated" "Compute")
	# we don't have to care about no change
	graphics=$(printf "%s\n" "${mode[@]}" | rofi -p "Graphics Mode" -dmenu)
	case "$graphics" in
	"Integrated")
		supergfxctl -m Integrated
		graphics i
		;;
	"Hybrid")
		supergfxctl -m Hybrid
		graphics h
		;;
	"Dedicated")
		supergfxctl -m Dedicated
		graphics d
		;;
	"Compute")
		supergfxctl -m Compute
		graphics c
		;;
	esac
}

case "$chosen" in
"${options[0]}")
	betterlockscreen -l
	;;
"${options[1]}")
	systemctl suspend
	;;
"${options[2]}")
	ask_graphics
	sleep 6s
	if [[ "$XDG_CURRENT_DESKTOP" == "KDE" ]]; then
		qdbus org.kde.Shutdown /Shutdown logoutAndShutdown
	else
		shutdown now
	fi
	;;
"${options[3]}")
	ask_graphics
	sleep 6s
	if [[ "$XDG_CURRENT_DESKTOP" == "KDE" ]]; then
		qdbus org.kde.Shutdown /Shutdown logoutAndReboot
	else
		reboot
	fi
	;;
"${options[4]}")
	ask_graphics
	if [[ "$XDG_CURRENT_DESKTOP" == "KDE" ]]; then
		qdbus org.kde.Shutdown /Shutdown logout
	else
		bspc quit
	fi
	;;
*) ;;
esac
