#! /usr/bin/env fish

set services "supergfxd" "mpd" "bluetooth" "gns3-server" "sshd" "docker" "postgresql" "libvirt" "cups" "xboxdrv"
set chosen $(printf "%s\n" $services | rofi -p "Services" -dmenu)

switch "$chosen"
case "supergfxd"
    systemctl start supergfxd
case "mpd"
    systemctl start --user mpd
case "bluetooth"
    systemctl start bluetooth
case "gns3-server"
    systemctl start "gns3-server@$USER"
case "sshd"
    systemctl start sshd
case "docker"
    systemctl start docker
case "postgresql"
    systemctl start postgresql
case "libvirt"
    systemctl start libvirtd
    sudo virsh net-start default
case "cups"
    systemctl start cups
case "xboxdrv"
    systemctl start xboxdrv
case "*"
    echo "This is not a valid service."
end
