#! /bin/sh

XRESOURCES="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"

# merge the xresources if there is one
[ -f "$XRESOURCES" ] && xrdb -merge "$XRESOURCES"

# decrease keyboard repeat delay and increase repeat rate
# xset r rate 200 45

# start the ibus daemon
# ibus-daemon -drxR

# start
# don't start anything if nothing is supplied
case "$1" in
i3) exec i3 ;;
awe) exec awesome ;;
gnome) exec gnome-session ;;
kde) exec startplasma-x11 ;;
bs) exec bspwm ;;
esac
