[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#17252A"
blue = "#92bbed"
cyan = "#80ffff"
green = "#A2E4B8"
magenta = "#ecc6e8"
red = "#E6676B"
white = "#cfebec"
yellow = "#e2d06a"

[colors.cursor]
cursor = "#d9d7d6"
text = "#c2cae2"

[colors.normal]
black = "#1b2c31"
blue = "#bdd6f4"
cyan = "#b3ffff"
green = "#AAF0C1"
magenta = "#f9ecf7"
red = "#FF7377"
white = "#edf7f8"
yellow = "#eadd94"

[colors.primary]
background = "#040c16"
foreground = "#cce9ea"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 3

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 8
y = 12
